CREATE TABLE Doctor(
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(250) NOT NULL,
	specialization VARCHAR(250) NOT NULL,
	degree VARCHAR(250) NOT NULL,
	state VARCHAR(250) NOT NULL,
	city VARCHAR(250) NOT NULL
);